# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_confirm_categ.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#from PyQt5.QtWidgets import QMainWindow, QApplication, QPushButton, QMessageBox, QComboBox, QFileDialog
#from PyQt5.QtGui import QStandardItemModel, QStandardItem
#from PyQt5.QtCore import pyqtSlot, QFile, QTextStream
#from PyQt5 import QtWidgets, QtGui, QtCore

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5 import QtCore
from PyQt5 import QtGui
import time
import sys
import os
from openpyxl import load_workbook, Workbook
#from f_delete_cc import BtnFunctions

#
from TRIAL_DELETE_CLICKED import ProceedDelete
#





class DeleteConfirmCat(object): #change to DeleteConfirmCat
    
    # ========== MY CODE ========== #
    def press_it(self):
        #sys.exit(qApp.exec_()) # to exit the window if cancel is clicked
        #self.quit()
        #self.hide()
        #Dialog.hide()
        Dialog.close()
        #self.close()
        #self.hide()
        #setupUi.hide()
        #self.show()

    def press_del(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = ProceedDelete() # from other py file
        self.ui.setupUi(self.window)
        self.window.show()
    #
    
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(659, 282)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 40, 200, 200))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../delete_warning.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

                                                            # CHANGE LATER
        self.delete_btn = QtWidgets.QPushButton(Dialog, clicked=lambda: self.press_del())
        self.delete_btn.setGeometry(QtCore.QRect(280, 190, 131, 41))


        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(9)
        self.delete_btn.setFont(font)
        self.delete_btn.setDefault(False)
        self.delete_btn.setFlat(False)
        self.delete_btn.setObjectName("delete_btn")

                                                        # ========== MY CODE ========== #
        self.pushButton_2 = QtWidgets.QPushButton(Dialog, clicked=lambda: self.press_it()) #, clicked=lambda: self.press_it()
        self.pushButton_2.setGeometry(QtCore.QRect(450, 190, 131, 41))
        #self.pushButton_2.clicked.connect(lambda:self.close())


        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(9)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(280, 30, 391, 71))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(280, 90, 391, 71))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
    


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.delete_btn.setText(_translate("Dialog", "Delete"))
        self.pushButton_2.setText(_translate("Dialog", "Cancel"))
        self.label_2.setText(_translate("Dialog", "Delete category"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p>Are you sure to delete the selected category?<br/>This can\'t be undone.</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = DeleteConfirmCat()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
    print("1")
